// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD38_ClxrRWJDnyCYVFIEmA2XOR_2wZYxs',
    appId: '1:181967608899:web:9dbf2830749600f3ffc8f6',
    messagingSenderId: '181967608899',
    projectId: 'note-1ab10',
    authDomain: 'note-1ab10.firebaseapp.com',
    storageBucket: 'note-1ab10.appspot.com',
    measurementId: 'G-CRTRDBFMJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChgQK7_1ZrVGGknHOOWV-QmSntuwLbzRc',
    appId: '1:181967608899:android:1bfddf4ef6099b28ffc8f6',
    messagingSenderId: '181967608899',
    projectId: 'note-1ab10',
    storageBucket: 'note-1ab10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj-RliT2ZrEl81xZcdH2v_Qc_BPgzelmc',
    appId: '1:181967608899:ios:0324fde4917afed5ffc8f6',
    messagingSenderId: '181967608899',
    projectId: 'note-1ab10',
    storageBucket: 'note-1ab10.appspot.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj-RliT2ZrEl81xZcdH2v_Qc_BPgzelmc',
    appId: '1:181967608899:ios:f0c7e6fe8094c307ffc8f6',
    messagingSenderId: '181967608899',
    projectId: 'note-1ab10',
    storageBucket: 'note-1ab10.appspot.com',
    iosBundleId: 'com.example.note.RunnerTests',
  );
}
